[project]
name = "chart"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "pyqt5>=5.15.11",
]

[project.scripts]
chart="main:main"
